var namespace_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction =
[
    [ "CashRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_cash_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_cash_request" ],
    [ "DepositRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_deposit_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_deposit_request" ],
    [ "FixedSurcharge", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_fixed_surcharge.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_fixed_surcharge" ],
    [ "FollowUpTransactionRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_follow_up_transaction_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_follow_up_transaction_request" ],
    [ "FollowUpTransactionRequestValidator", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_follow_up_transaction_request_validator.html", null ],
    [ "PercentageSurcharge", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_percentage_surcharge.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_percentage_surcharge" ],
    [ "PreAuthCancelRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_cancel_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_cancel_request" ],
    [ "PreAuthCompletionRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_completion_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_completion_request" ],
    [ "PreAuthExtendRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_extend_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_extend_request" ],
    [ "PreAuthInquiryRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_inquiry_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_inquiry_request" ],
    [ "PreAuthManipulationRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_manipulation_request.html", null ],
    [ "PreAuthManipulationRequestValidator", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_manipulation_request_validator.html", null ],
    [ "PreAuthPartialCancelRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_partial_cancel_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_partial_cancel_request" ],
    [ "PreAuthRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_request" ],
    [ "PreAuthSummaryRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_summary_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_summary_request" ],
    [ "PreAuthTopUpRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_top_up_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_pre_auth_top_up_request" ],
    [ "PurchaseRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_purchase_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_purchase_request" ],
    [ "RefundRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_refund_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_refund_request" ],
    [ "RetrieveTransactionRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_retrieve_transaction_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_retrieve_transaction_request" ],
    [ "SurchargeOptions", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_surcharge_options.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_surcharge_options" ],
    [ "SurchargeRule", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_surcharge_rule.html", null ],
    [ "TippingOptions", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_tipping_options.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_tipping_options" ],
    [ "TransactionFlags", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_transaction_flags.html", null ],
    [ "TransactionRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_transaction_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_transaction_request" ],
    [ "TransactionResponse", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_transaction_response.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_transaction_response" ],
    [ "VoidRequest", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_void_request.html", "class_linkly_1_1_pos_api_1_1_sdk_1_1_models_1_1_transaction_1_1_void_request" ]
];